pybullet build time: Jan 24 2022 10:59:54
Traceback (most recent call last):
  File "/Users/jaketeneyck/Desktop/mybots/simulate.py", line 7, in <module>
    simulation = SIMULATION(directOrGUI, solutionID)
  File "/Users/jaketeneyck/Desktop/mybots/simulation.py", line 19, in __init__
    p.setAdditionalSearchPath(pybullet_data.getDataPath())
pybullet.error: Not connected to physics server.
Exception ignored in: <function SIMULATION.__del__ at 0x110bbb7f0>
Traceback (most recent call last):
  File "/Users/jaketeneyck/Desktop/mybots/simulation.py", line 31, in __del__
    p.disconnect()
pybullet.error: Not connected to physics server.
